name: MyStocksApp
options:
  bundleIdPrefix: com.yantraworks
  deploymentTarget:
    iOS: "17.0"

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic

targets:
  MyStocksApp:
    type: application
    platform: iOS
    sources:
      - path: MyStocksApp
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yantraworks.mystocksapp
        INFOPLIST_FILE: MyStocksApp/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_ENTITLEMENTS: MyStocksApp/MyStocksApp.entitlements
        ENABLE_PREVIEWS: YES
        SWIFT_VERSION: "5.9"
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: YES
    entitlements:
      path: MyStocksApp/MyStocksApp.entitlements
